spring:
  application:
    name: gatewayDemo

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /api/user/${segment}
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/order/**     # Gateway expects /order, not /api/order
          filters:
            - RewritePath=/api/order/(?<segment>.*), /api/order/${segment}
      metrics:
        enabled: true

server:
  port: 8282

management:
  endpoints:
    web:
      exposure:
        include: "gateway,health,info"
  endpoint:
    gateway:
      enabled: true
