spring:
  application:
    name: gatewayDemo

  cloud:
    spring:
      gateway:
        discovery:
          locator:
            enabled: true
        routes:
          - id: user-service
            uri: http://localhost:8083
            predicates:
              - Path=/user/**
          - id: order-service
            uri: http://localhost:8084
            predicates:
              - Path=/order/**
            filters:
              - PrefixPath=/api
        metrics:
          enabled: true

server:
  port: 8082